[package]
name = "mosaic-model"
version = "0.1.1"
edition = "2024"
repository = "https://github.com/gusjengis/Mosaic-Model"
description = "The data model for Mosaic"
license = "MIT OR Apache-2.0"

[dependencies]
